apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics
data:
  DB_USERNAME: "postgres"
  DB_HOST: "postgresql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: analytics
  name: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
      - image: 914303283224.dkr.ecr.us-east-1.amazonaws.com/udacity-project-ecr:0.0.1
        name: analytics
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: analytics
              key: DB_USERNAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: analytics
              key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: udacity
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: analytics
spec:
  selector:
    app: analytics
  ports:
    - protocol: TCP
      port: 5153
      targetPort: 5153
  type: LoadBalancer